### ISSUE TITLE
Provide docker container

### ISSUE THREAD

**Issue by cromefire** [MadCamel/acmeproxy.pl#1]
Hi, this looks quite nice and so my question would be if it is possible to provide a docker container for this? I've never worked with perl before an honestly don't plan to set it up onto my server bare metal (haven't tried it yet, but definitely keen on trying it), but I think a docker container would make it easier to set up and also easy to daemonize it.

Maybe I'll find some time to contribute docker support myself, but I can't promise that.

**Comment by MadCamel** [comment]
Thanks for the input! 

My view is that this was designed to be extremely easy to get going on bare metal, docker would just add extra steps. Give it a try and you might see what I mean.

Regardless, here's a basic and untested Dockerfile for you to try. You're welcome to polish it up and make a PR.  If you do so please include instructions on how to use it in the README. 


```
FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    libmojolicious-perl \
    curl

WORKDIR /app
COPY . /app

CMD [ "perl", "/app/acmeproxy.pl" ]
```

**Comment by cromefire** [comment]
> My view is that this was designed to be extremely easy to get going on bare metal, docker would just add extra steps. Give it a try and you might see what I mean.

I made the experience that managing language runtimes and services on bare metal always leads to weired incompatibilities and stuff, so I just have basically anything in docker now and managing and updating every application is just `sudo docker compose pull && sudo docker compose up -d`.

Made a PR BTW, still have to test it, but should work fine,
